/**
 * AI Tools Database — aikompass.cz
 * 35+ nástrojů s filtrováním podle kategorie, ceny, češtiny, free tieru
 */

export type ToolCategory =
  | "psani"
  | "obrazky"
  | "video"
  | "kod"
  | "seo"
  | "produktivita";

export type CzechSupport = "ano" | "castecne" | "ne";

export interface AiTool {
  id: string;
  name: string;
  description: string;
  longDescription?: string;
  category: ToolCategory;
  /** Cena v USD/měsíc pro nejlevnější placený plán. null = zdarma. */
  priceFrom: number | null;
  freeTier: boolean;
  czech: CzechSupport;
  rating: number; // 1.0–5.0
  affiliateUrl: string;
  websiteUrl: string;
  mainFeatures: string[];
  gdpr: "ok" | "castecne" | "riziko";
  /** Jméno firmy / původ */
  vendor: string;
}

export const CATEGORY_LABELS: Record<ToolCategory, { label: string; icon: string }> = {
  psani:        { label: "Psaní",        icon: "✍️" },
  obrazky:      { label: "Obrázky",      icon: "🖼️" },
  video:        { label: "Video",        icon: "🎬" },
  kod:          { label: "Kód",          icon: "💻" },
  seo:          { label: "SEO",          icon: "🔍" },
  produktivita: { label: "Produktivita", icon: "⚡" },
};

export const CZECH_LABELS: Record<CzechSupport, string> = {
  ano:      "Ano",
  castecne: "Částečně",
  ne:       "Ne",
};

export const AI_TOOLS: AiTool[] = [
  // ── PSANÍ ────────────────────────────────────────────────────────────────
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: "Nejpopulárnější AI asistent od OpenAI. Psaní, shrnutí, překlady, kód i analýzy.",
    category: "psani",
    priceFrom: 20,
    freeTier: true,
    czech: "castecne",
    rating: 4.8,
    affiliateUrl: "https://chat.openai.com",
    websiteUrl: "https://chat.openai.com",
    mainFeatures: ["GPT-4o", "Tvorba obrázků (DALL-E)", "Analýza souborů", "Vlastní GPTs"],
    gdpr: "castecne",
    vendor: "OpenAI (USA)",
  },
  {
    id: "claude",
    name: "Claude",
    description: "AI asistent od Anthropic s důrazem na bezpečnost a dlouhý kontext. Skvělý na psaní a analýzu.",
    category: "psani",
    priceFrom: 20,
    freeTier: true,
    czech: "castecne",
    rating: 4.9,
    affiliateUrl: "https://claude.ai",
    websiteUrl: "https://claude.ai",
    mainFeatures: ["200K tokenů kontext", "Analýza dokumentů", "Kódování", "Výzkum"],
    gdpr: "castecne",
    vendor: "Anthropic (USA)",
  },
  {
    id: "jasper",
    name: "Jasper AI",
    description: "Profesionální AI copywriting nástroj. Šablony pro marketing, blogy a sociální sítě.",
    category: "psani",
    priceFrom: 39,
    freeTier: false,
    czech: "ne",
    rating: 4.2,
    affiliateUrl: "https://www.jasper.ai",
    websiteUrl: "https://www.jasper.ai",
    mainFeatures: ["50+ šablon", "Tone of voice", "SEO integrace", "Brandová paměť"],
    gdpr: "castecne",
    vendor: "Jasper (USA)",
  },
  {
    id: "copyai",
    name: "Copy.ai",
    description: "AI psaní pro marketing a e-commerce. Rychlé texty pro reklamy, produkty a emaily.",
    category: "psani",
    priceFrom: 36,
    freeTier: true,
    czech: "ne",
    rating: 4.0,
    affiliateUrl: "https://www.copy.ai",
    websiteUrl: "https://www.copy.ai",
    mainFeatures: ["Marketing texty", "E-mailové sekvence", "Produktové popisy", "Workflow automatizace"],
    gdpr: "castecne",
    vendor: "Copy.ai (USA)",
  },
  {
    id: "writesonic",
    name: "Writesonic",
    description: "Rychlý AI pro tvorbu obsahu — články, reklamy, landing pages a faktické texty.",
    category: "psani",
    priceFrom: 16,
    freeTier: true,
    czech: "ne",
    rating: 4.1,
    affiliateUrl: "https://writesonic.com",
    websiteUrl: "https://writesonic.com",
    mainFeatures: ["Faktické psaní", "Botsonic chatbot", "Bulkové generování", "Google Search integrace"],
    gdpr: "castecne",
    vendor: "Writesonic (USA)",
  },
  {
    id: "grammarly",
    name: "Grammarly",
    description: "AI editor pro gramatiku, styl a tón. Funguje jako rozšíření ve všech aplikacích.",
    category: "psani",
    priceFrom: 12,
    freeTier: true,
    czech: "ne",
    rating: 4.4,
    affiliateUrl: "https://www.grammarly.com",
    websiteUrl: "https://www.grammarly.com",
    mainFeatures: ["Gramatika a pravopis", "Styl a tón", "Plagiarismus check", "Prohlížečové rozšíření"],
    gdpr: "castecne",
    vendor: "Grammarly (USA)",
  },

  // ── OBRÁZKY ──────────────────────────────────────────────────────────────
  {
    id: "midjourney",
    name: "Midjourney",
    description: "Nejkvalitnější AI generátor obrázků. Umělecký styl, detailní vizuály, fotorealistika.",
    category: "obrazky",
    priceFrom: 10,
    freeTier: false,
    czech: "ne",
    rating: 4.7,
    affiliateUrl: "https://www.midjourney.com",
    websiteUrl: "https://www.midjourney.com",
    mainFeatures: ["V6 model", "Styl konzistence", "Vary Region", "Discord + Web UI"],
    gdpr: "riziko",
    vendor: "Midjourney (USA)",
  },
  {
    id: "dalle3",
    name: "DALL-E 3",
    description: "OpenAI generátor obrázků integrovaný v ChatGPT. Nejlepší pro přesné zachycení promptu.",
    category: "obrazky",
    priceFrom: 20,
    freeTier: false,
    czech: "castecne",
    rating: 4.5,
    affiliateUrl: "https://chat.openai.com",
    websiteUrl: "https://openai.com/dall-e-3",
    mainFeatures: ["Přesné zachycení promptu", "ChatGPT integrace", "Text v obrázcích", "HD výstup"],
    gdpr: "castecne",
    vendor: "OpenAI (USA)",
  },
  {
    id: "adobefirefly",
    name: "Adobe Firefly",
    description: "Generativní AI od Adobe. Trénovaný na licencovaném obsahu — bezpečné pro komerční použití.",
    category: "obrazky",
    priceFrom: 5,
    freeTier: true,
    czech: "ne",
    rating: 4.4,
    affiliateUrl: "https://www.adobe.com/products/firefly.html",
    websiteUrl: "https://www.adobe.com/products/firefly.html",
    mainFeatures: ["Komerčně bezpečné", "Photoshop integrace", "Generative Fill", "Text efekty"],
    gdpr: "ok",
    vendor: "Adobe (USA)",
  },
  {
    id: "canva",
    name: "Canva AI",
    description: "Vizuální editor s AI funkcemi — generování obrázků, pozadí, magic resize a texty.",
    category: "obrazky",
    priceFrom: 13,
    freeTier: true,
    czech: "castecne",
    rating: 4.6,
    affiliateUrl: "https://www.canva.com",
    websiteUrl: "https://www.canva.com",
    mainFeatures: ["Drag & drop editor", "Magic Studio", "Šablony", "Brand Kit"],
    gdpr: "castecne",
    vendor: "Canva (AU)",
  },
  {
    id: "leonardoai",
    name: "Leonardo AI",
    description: "AI generátor obrázků s důrazem na herní a fantastický obsah. Velká komunita modelů.",
    category: "obrazky",
    priceFrom: 10,
    freeTier: true,
    czech: "ne",
    rating: 4.3,
    affiliateUrl: "https://leonardo.ai",
    websiteUrl: "https://leonardo.ai",
    mainFeatures: ["Vlastní modely", "ControlNet", "Image2Image", "Motion generování"],
    gdpr: "castecne",
    vendor: "Leonardo AI (AU)",
  },
  {
    id: "ideogram",
    name: "Ideogram",
    description: "AI generátor obrázků vynikající v přesném generování textu uvnitř obrázků.",
    category: "obrazky",
    priceFrom: 8,
    freeTier: true,
    czech: "ne",
    rating: 4.3,
    affiliateUrl: "https://ideogram.ai",
    websiteUrl: "https://ideogram.ai",
    mainFeatures: ["Text v obrázcích", "Typography", "Realism mód", "Magic prompt"],
    gdpr: "castecne",
    vendor: "Ideogram (USA)",
  },

  // ── VIDEO ─────────────────────────────────────────────────────────────────
  {
    id: "runway",
    name: "Runway ML",
    description: "Profesionální AI video generátor. Gen-3 model pro realistická videa z textu nebo obrázku.",
    category: "video",
    priceFrom: 15,
    freeTier: true,
    czech: "ne",
    rating: 4.5,
    affiliateUrl: "https://runwayml.com",
    websiteUrl: "https://runwayml.com",
    mainFeatures: ["Gen-3 Alpha", "Text-to-video", "Image-to-video", "Video editace"],
    gdpr: "castecne",
    vendor: "Runway (USA)",
  },
  {
    id: "heygen",
    name: "HeyGen",
    description: "AI avatar video — vytvoř video s mluvícím avatarem bez kamery. Překlad videa do 40 jazyků.",
    category: "video",
    priceFrom: 29,
    freeTier: true,
    czech: "castecne",
    rating: 4.4,
    affiliateUrl: "https://www.heygen.com",
    websiteUrl: "https://www.heygen.com",
    mainFeatures: ["AI avatary", "Video překlad", "Lip sync", "Vlastní avatar"],
    gdpr: "castecne",
    vendor: "HeyGen (USA)",
  },
  {
    id: "synthesia",
    name: "Synthesia",
    description: "Enterprise AI video platforma. Profesionální avatary, více než 120 jazyků.",
    category: "video",
    priceFrom: 22,
    freeTier: false,
    czech: "castecne",
    rating: 4.3,
    affiliateUrl: "https://www.synthesia.io",
    websiteUrl: "https://www.synthesia.io",
    mainFeatures: ["120+ jazyků", "Firemní avatary", "SCORM export", "Šablony"],
    gdpr: "ok",
    vendor: "Synthesia (UK)",
  },
  {
    id: "pika",
    name: "Pika",
    description: "Rychlý AI video generátor — animace z obrázků, efekty, krátká videa.",
    category: "video",
    priceFrom: 8,
    freeTier: true,
    czech: "ne",
    rating: 4.1,
    affiliateUrl: "https://pika.art",
    websiteUrl: "https://pika.art",
    mainFeatures: ["Image-to-video", "Pikaffects efekty", "4K výstup", "Rychlé generování"],
    gdpr: "castecne",
    vendor: "Pika Labs (USA)",
  },

  // ── KÓD ───────────────────────────────────────────────────────────────────
  {
    id: "githubcopilot",
    name: "GitHub Copilot",
    description: "AI asistent pro programátory přímo ve VS Code. Doplňuje kód, generuje testy, vysvětluje chyby.",
    category: "kod",
    priceFrom: 10,
    freeTier: true,
    czech: "ne",
    rating: 4.7,
    affiliateUrl: "https://github.com/features/copilot",
    websiteUrl: "https://github.com/features/copilot",
    mainFeatures: ["Autocomplete", "Chat", "Generování testů", "PR vysvětlení"],
    gdpr: "castecne",
    vendor: "GitHub / Microsoft (USA)",
  },
  {
    id: "cursor",
    name: "Cursor",
    description: "AI-first editor postavený na VS Code. Celé soubory upraví jedním promptem, chápe celý projekt.",
    category: "kod",
    priceFrom: 20,
    freeTier: true,
    czech: "ne",
    rating: 4.8,
    affiliateUrl: "https://www.cursor.com",
    websiteUrl: "https://www.cursor.com",
    mainFeatures: ["Composer (multi-file)", "Codebase chat", "Claude & GPT-4o", "Inline edit"],
    gdpr: "castecne",
    vendor: "Anysphere (USA)",
  },
  {
    id: "codeium",
    name: "Codeium",
    description: "Bezplatný AI asistent pro kód. Rychlé dokončování ve všech populárních editorech.",
    category: "kod",
    priceFrom: null,
    freeTier: true,
    czech: "ne",
    rating: 4.5,
    affiliateUrl: "https://codeium.com",
    websiteUrl: "https://codeium.com",
    mainFeatures: ["Zdarma pro jednotlivce", "70+ editorů", "Autocomplete", "Chat"],
    gdpr: "castecne",
    vendor: "Exafunction (USA)",
  },
  {
    id: "tabnine",
    name: "Tabnine",
    description: "AI code completion s možností lokálního běhu. Větší soukromí pro firemní použití.",
    category: "kod",
    priceFrom: 12,
    freeTier: true,
    czech: "ne",
    rating: 4.2,
    affiliateUrl: "https://www.tabnine.com",
    websiteUrl: "https://www.tabnine.com",
    mainFeatures: ["Lokální mód", "Firemní ochrana kódu", "IDE integrace", "Code review"],
    gdpr: "ok",
    vendor: "Tabnine (Izrael)",
  },
  {
    id: "v0",
    name: "v0 (Vercel)",
    description: "AI generátor React UI komponent. Z textu nebo screenshotu vygeneruje hotový kód.",
    category: "kod",
    priceFrom: 20,
    freeTier: true,
    czech: "ne",
    rating: 4.4,
    affiliateUrl: "https://v0.dev",
    websiteUrl: "https://v0.dev",
    mainFeatures: ["React komponenty", "Tailwind CSS", "Shadcn/ui", "Live preview"],
    gdpr: "castecne",
    vendor: "Vercel (USA)",
  },

  // ── SEO ───────────────────────────────────────────────────────────────────
  {
    id: "surferseo",
    name: "Surfer SEO",
    description: "AI SEO nástroj pro optimalizaci obsahu. Analýza SERP, NLP klíčová slova, content score.",
    category: "seo",
    priceFrom: 79,
    freeTier: false,
    czech: "ne",
    rating: 4.4,
    affiliateUrl: "https://surferseo.com",
    websiteUrl: "https://surferseo.com",
    mainFeatures: ["Content editor", "SERP analýza", "Keyword research", "AI writer"],
    gdpr: "castecne",
    vendor: "Surfer (Polsko)",
  },
  {
    id: "frase",
    name: "Frase.io",
    description: "AI SEO psaní a výzkum klíčových slov. Rychlá tvorba SEO článků s faktickými daty.",
    category: "seo",
    priceFrom: 15,
    freeTier: false,
    czech: "ne",
    rating: 4.2,
    affiliateUrl: "https://www.frase.io",
    websiteUrl: "https://www.frase.io",
    mainFeatures: ["Content brief", "SERP research", "AI psaní", "Optimalizace"],
    gdpr: "castecne",
    vendor: "Frase (USA)",
  },
  {
    id: "seowind",
    name: "SEOwind",
    description: "AI nástroj pro tvorbu SEO článků s reálnými daty. Propojení s GSC a Semrush.",
    category: "seo",
    priceFrom: 49,
    freeTier: false,
    czech: "ne",
    rating: 4.0,
    affiliateUrl: "https://seowind.io",
    websiteUrl: "https://seowind.io",
    mainFeatures: ["GSC integrace", "AI SEO články", "Competitor analýza", "FAQ generování"],
    gdpr: "castecne",
    vendor: "SEOwind (Polsko)",
  },
  {
    id: "semrush-ai",
    name: "Semrush AI Writing Assistant",
    description: "AI psaní integrované přímo v Semrush. SEO skóre v reálném čase při psaní.",
    category: "seo",
    priceFrom: 130,
    freeTier: false,
    czech: "ne",
    rating: 4.3,
    affiliateUrl: "https://www.semrush.com/seo-writing-assistant/",
    websiteUrl: "https://www.semrush.com",
    mainFeatures: ["SEO optimalizace v reálném čase", "Tone checker", "Plagiarismus", "Rephraser"],
    gdpr: "castecne",
    vendor: "Semrush (USA)",
  },

  // ── PRODUKTIVITA ──────────────────────────────────────────────────────────
  {
    id: "notionai",
    name: "Notion AI",
    description: "AI přímo ve workspace Notion. Psaní, shrnutí, překlady a Q&A nad tvojí databází.",
    category: "produktivita",
    priceFrom: 10,
    freeTier: false,
    czech: "castecne",
    rating: 4.3,
    affiliateUrl: "https://www.notion.so/product/ai",
    websiteUrl: "https://www.notion.so",
    mainFeatures: ["AI psaní", "Shrnutí stránek", "Q&A nad databází", "Překlad"],
    gdpr: "castecne",
    vendor: "Notion Labs (USA)",
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    description: "AI vyhledávač který odpovídá s citacemi ze zdrojů. Nejlepší pro výzkum a aktuální info.",
    category: "produktivita",
    priceFrom: 20,
    freeTier: true,
    czech: "castecne",
    rating: 4.6,
    affiliateUrl: "https://www.perplexity.ai",
    websiteUrl: "https://www.perplexity.ai",
    mainFeatures: ["Citované odpovědi", "Webový přístup", "Spaces pro výzkum", "Sonar API"],
    gdpr: "castecne",
    vendor: "Perplexity AI (USA)",
  },
  {
    id: "make",
    name: "Make (Integromat)",
    description: "Vizuální automatizační platforma s AI. Propojení stovek aplikací, česká podpora.",
    category: "produktivita",
    priceFrom: 9,
    freeTier: true,
    czech: "ano",
    rating: 4.5,
    affiliateUrl: "https://www.make.com",
    websiteUrl: "https://www.make.com",
    mainFeatures: ["Vizuální editor", "1000+ aplikací", "AI moduly", "Česká podpora"],
    gdpr: "ok",
    vendor: "Make (CZ — Celonis)",
  },
  {
    id: "zapier",
    name: "Zapier AI",
    description: "Nejrozšířenější automatizační platforma. AI asistent pro tvorbu workflowů bez kódu.",
    category: "produktivita",
    priceFrom: 20,
    freeTier: true,
    czech: "castecne",
    rating: 4.2,
    affiliateUrl: "https://zapier.com",
    websiteUrl: "https://zapier.com",
    mainFeatures: ["7000+ aplikací", "AI Zaps", "Tables & Canvas", "Chatbots"],
    gdpr: "castecne",
    vendor: "Zapier (USA)",
  },
  {
    id: "otter",
    name: "Otter.ai",
    description: "AI přepis meetingů v reálném čase. Automatické shrnutí, akční body, integrace do Zoom/Teams.",
    category: "produktivita",
    priceFrom: 10,
    freeTier: true,
    czech: "ne",
    rating: 4.3,
    affiliateUrl: "https://otter.ai",
    websiteUrl: "https://otter.ai",
    mainFeatures: ["Přepis v reálném čase", "Meeting shrnutí", "Zoom/Teams integrace", "Prohledávání"],
    gdpr: "castecne",
    vendor: "Otter.ai (USA)",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "AI hlasová syntéza — nejreálnější hlasy na trhu. Klonování hlasu, vícejazyčný TTS.",
    category: "produktivita",
    priceFrom: 5,
    freeTier: true,
    czech: "castecne",
    rating: 4.7,
    affiliateUrl: "https://elevenlabs.io",
    websiteUrl: "https://elevenlabs.io",
    mainFeatures: ["Klonování hlasu", "29+ jazyků", "TTS API", "Audio story"],
    gdpr: "castecne",
    vendor: "ElevenLabs (USA)",
  },
  {
    id: "microsoftcopilot",
    name: "Microsoft Copilot",
    description: "AI asistent od Microsoftu integrovaný do Office 365 — Word, Excel, Teams, Outlook.",
    category: "produktivita",
    priceFrom: 30,
    freeTier: true,
    czech: "castecne",
    rating: 4.2,
    affiliateUrl: "https://copilot.microsoft.com",
    websiteUrl: "https://copilot.microsoft.com",
    mainFeatures: ["Office 365 integrace", "Teams shrnutí", "Excel analýzy", "Outlook drafty"],
    gdpr: "ok",
    vendor: "Microsoft (USA)",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    description: "AI asistent od Googlu s přístupem k webu, Google Docs, Gmail a dalším službám.",
    category: "produktivita",
    priceFrom: 20,
    freeTier: true,
    czech: "castecne",
    rating: 4.3,
    affiliateUrl: "https://gemini.google.com",
    websiteUrl: "https://gemini.google.com",
    mainFeatures: ["Google Workspace integrace", "Gemini 1.5 Pro", "Webový přístup", "Multimodální"],
    gdpr: "castecne",
    vendor: "Google (USA)",
  },
];

/** Vrátí filtrované nástroje */
export function filterTools(tools: AiTool[], opts: {
  category?: ToolCategory | "vse";
  maxPrice?: number | null;
  czech?: CzechSupport | "vse";
  freeTierOnly?: boolean;
}): AiTool[] {
  return tools.filter((t) => {
    if (opts.category && opts.category !== "vse" && t.category !== opts.category) return false;
    if (opts.freeTierOnly && !t.freeTier) return false;
    if (opts.czech && opts.czech !== "vse" && t.czech !== opts.czech) return false;
    if (opts.maxPrice != null) {
      const price = t.priceFrom ?? 0;
      if (price > opts.maxPrice) return false;
    }
    return true;
  });
}
